const MIXPANEL_EVENTS = [
  "ADDED_ALERT",
  "COMMAND_FAILED",
  "COMMAND_NOT_FOUND",
  "DEPLOYED_COMMANDS",
  "LISTED_MONSTER_CODES",
  "LOGGED_IN",
  "INVALID_MONSTER_CODE",
  "JOINED_SERVER",
  "REMOVED_ALERT",
  "RESET_SPAWN",
  "SENT_ALERT",
  "VIEWED_SPAWN_INFO",
] as const;
export type MixpanelEvent = (typeof MIXPANEL_EVENTS)[number];
