# Deploys the master branch to the server to run the bot.

name: deploy-prod

on:
  push:
    branches: [master]

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Go into the repository directory
      - name: Going into the repository directory
        run: cd $GITHUB_WORKSPACE

      # Create the env file
      - name: Creating the env file
        run: |
          touch .env
          echo DISCORD_APPLICATION_TOKEN=${{ secrets.DISCORD_APPLICATION_TOKEN }} >> .env
          echo DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} >> .env
          echo MIXPANEL_TOKEN=${{ secrets.MIXPANEL_TOKEN }} >> .env

      # Builds the app
      - name: Building the app
        run: npm i && npm run build

      # Set up a place to store the private key
      - name: Creating a temp private key file
        run: echo "TEMP_PRIVATE_KEY_FILE=../private_key.pem" >> $GITHUB_ENV

      # Writing the private key to the temp file
      - name: Writing the private key to the temp file
        run: printf "%s" "${{ secrets.DEPLOY_BOT_PRIVATE_KEY }}" >${{ env.TEMP_PRIVATE_KEY_FILE}}

      # Avoid the permissions too open error on the private key
      - name: Changing the permissions for the private key
        run: chmod 600 ${{ env.TEMP_PRIVATE_KEY_FILE}}

      # Using rsync to copy files to the server
      - name: Copying files to the server
        run: rsync --delete -zrpv -e "ssh -o StrictHostKeyChecking=no -i ${{ env.TEMP_PRIVATE_KEY_FILE}}" $GITHUB_WORKSPACE/ ${{ secrets.DEPLOY_BOT_USERNAME }}@${{ secrets.HERGBOT_WEB_SERVER }}:/var/app/grandmaster-botlin/
